name: Build & Release Arqut Edge CE

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Related Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.0.1"
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"

      - name: Build UI
        working-directory: ./ui
        run: |
          npm install
          npm run build

      - name: Build Binary with GoReleaser
        run: |
          set -e
          go version
          curl -sfL https://goreleaser.com/static/run | bash -s -- release --skip=announce,publish,validate --clean

          mkdir -p releases
          mv dist/arqut-edge-ce_linux_arm_7 releases/arqut-edge-ce_linux-armv7
          mv dist/arqut-edge-ce_linux_arm_6 releases/arqut-edge-ce_linux-armv6
          mv dist/arqut-edge-ce_linux_arm64_v8.0 releases/arqut-edge-ce_linux-aarch64
          mv dist/arqut-edge-ce_linux_amd64_v1 releases/arqut-edge-ce_linux-amd64
          mv dist/arqut-edge-ce_linux_386_sse2 releases/arqut-edge-ce_linux-i386

      - name: Create GitHub Release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for Arqut Edge CE"
          files: releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: releases/
          overwrite: true
          retention-days: 7
